### ISSUE TITLE
Missing packages in requirements.txt

### ISSUE THREAD

**Issue by jodmoreira** [jcchouinard/GoogleSearchConsole-Tutorial#1]
You are using Pandas and dateutil in your code but not calling then on requirements.txt
Anyway good job! =)

**Comment by benjaminwsebastian** [comment]
For anyone who may see this and not know how to resolve the issue:

Method 1:

`pip install python-dateutil pandas`

Method 2:

`python -m pip install python-dateutil pandas`

**Comment by jcchouinard** [comment]
Updated. Thanks.
